export type AiContractErrorCode =
  | 'AI_CONTEXT_INVALID'
  | 'AI_CONTEXT_TARGET_UNAVAILABLE'
  | 'AI_CONTEXT_TARGET_AMBIGUOUS'
  | 'AI_PROMPT_INVALID'
  | 'AI_PROMPT_MODE_INVALID'
  | 'AI_PROMPT_INPUT_TOO_LARGE'
  | 'AI_COACHING_REQUEST_INVALID'
  | 'AI_LEARNING_REQUEST_INVALID'
  | 'AI_LEARNING_SOURCE_UNAVAILABLE'
  | 'AI_LEARNING_PROVENANCE_INVALID'
  | 'AI_LEARNING_TARGET_MISMATCH'
  | 'AI_STRUCTURED_OUTPUT_INVALID'
  | 'AI_POST_ROOM_CONSENT_INVALID'
  | 'AI_POST_ROOM_CONSENT_REQUIRED'
  | 'AI_POST_ROOM_CONSENT_REVOKED'
  | 'AI_POST_ROOM_AUTHORIZATION'
  | 'AI_POST_ROOM_SOURCE_INELIGIBLE'
  | 'AI_POST_ROOM_RESULT_INVALID';

export class AiContractError extends Error {
  readonly name = 'AiContractError';

  constructor(
    readonly code: AiContractErrorCode,
    message: string,
  ) {
    super(message);
  }
}
